services:

  postgres:
    image: postgres:16
    container_name: crm-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: school_system
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    image: mandar0333/crm-backend:latest
    container_name: crm-backend
    depends_on:
      - postgres
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgresql://postgres:1234@postgres:5432/school_system?schema=public
      JWT_SECRET: supersafejwtkey123
      JWT_REFRESH_SECRET: supersaferefreshkey456
      PORT: 5000

  frontend:
    image: mandar0333/crm-frontend:latest
    container_name: crm-frontend
    depends_on:
      - backend
    ports:
      - "3000:80"

volumes:
  postgres_data:
